language: python
branches:
  only:
    - master
before_install:
install:
  - pip install -r requirements.txt
  - pip install ghp-import==0.5.5
script: make html
deploy:
  on:
    branch: master
  provider: script
  script: make travis_deploy
